# -*- coding: utf-8 -*-
"""ChatGPT Bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RMaEEVKCtCGnHcLCocJgSGD-w1vZVXyJ
"""



import openai

api_key = "sk-8BMOVnQ5gpTGGFJXWTPQT3B1bkFJiT8XIC3D11UPWPFOeAsL"

openai.api_key = api_key

def chat_with_bot(user_input):
    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=user_input,
        max_tokens=50
    )
    bot_response = response.choices[0].text.strip()
    return bot_response


while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        break

    bot_response = chat_with_bot(user_input)
    print(f"Chatbot: {bot_response}")